### ISSUE TITLE
Circular Reference with Generic Parameterization - error TS2456: Type alias 'Result' circularly references itself. #61062

### ISSUE THREAD

**Issue by AaronNGray** [AaronNGray/TypeScript#2]
### 🔎 Search Terms

https://github.com/microsoft/TypeScript/issues/61062 Self Referential Types, Recursive Types, Mutually Recursive Types.

### 🕗 Version & Regression Information

Failing on Main 32ebd28578902d5437e541cf185ea2a32742686d

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAggdiAPAFShAHsCcAmBnKAeQCMArCAY2AD4oBeKAbwCgo2oBtAawhAC48wAE4BLOAHMAunyjIA3MwC+cqM2ahIUAEoQ8AVwA2welEGiJUAD7bdh4B0lXYCRDv1HqKgPRe0QoQD2QrIAygBMACwArABsMsjg0ACGBiJJBADkbnYZUBQiQhSGSUIGIFBCEABmEJVwFLpQIsB4EAZVAHTMQA

### 💻 Code

Fails :-
```ts
type Any<T extends Object> = {
    [key:string]: T;
}; 

type Result = string | Result[] | Any<Result>; // error TS2456: Type alias 'Result' circularly references itself.
```
Works :-
```
type ResultObject = {
    [key:string]: Result;
}; 

type Result = string | Result[] | ResultObject;
```
Fails :-
```
type ResultObject = {
    [key:string]: Result;
}; 

type ResultArray<T> = T[];
 
type Result = string | ResultArray<Result> | ResultObject;  // error TS2456: Type alias 'Result' circularly references itself.
```
It looks like it is a Generic Parameterization issue.

### 🙁 Actual behavior

Throwing Error on compilation error TS2456: Type alias 'Result' circularly references itself.

### 🙂 Expected behavior

To support self referential, recursive, and mutually recursive types.
